### ISSUE TITLE
Exception during execution

### ISSUE THREAD

**Issue by djarb** [ReaperAnon/GridTransitionCrashFix#1]
I'm running it in Synthesis

Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Noggog.BinaryMemoryReadStream.ReadUInt16() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Streams\Binary\BinaryMemoryReadStream.cs:line 151
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryCreateTranslation.ReadEntries(MutagenFrame frame, UInt16 objectFormat)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay.CustomCtor()
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay.QuestAdapterFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, Nullable`1 parseParams)
   at Mutagen.Bethesda.Skyrim.Internals.QuestBinaryOverlay.get_VirtualMachineAdapter()
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuest item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuestInternal item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopy(IQuestGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.Skyrim.QuestMixIn.DeepCopy(IQuestGetter item, TranslationMask copyMask)
   at GridTrasitionCrashFix.Program.RunPatch(IPatcherState`2 state) in C:\Users\djarb\AppData\Local\Temp\Synthesis\e0osghvr.5yq\Git\2i0ws2zl.mwg\Runner\GridTrasitionCrashFix\Program.cs:line 23
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 68

**Comment by RoorMakurosu** [comment]
I have the same issue:

Running patch.
Changed multiple conditions in QUST _M_QuestFalskaarCourierLetterHigh
Changed multiple conditions in QUST _M_QuestFalskaarCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestFalskaarCourierPotionHigh
Changed multiple conditions in QUST _M_QuestSolstheimCourierLetterHigh
Changed multiple conditions in QUST _M_QuestSolstheimCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestSolstheimCourierPotionHigh
Changed multiple conditions in QUST _M_QuestMidwoodCourierLetterHigh
Changed multiple conditions in QUST _M_QuestMidwoodCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestMidwoodCourierPotionHigh
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Noggog.BinaryMemoryReadStream.ReadUInt16() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Streams\Binary\BinaryMemoryReadStream.cs:line 151
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryCreateTranslation.ReadEntries(MutagenFrame frame, UInt16 objectFormat)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay.CustomCtor()
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay.QuestAdapterFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, Nullable`1 parseParams)
   at Mutagen.Bethesda.Skyrim.Internals.QuestBinaryOverlay.get_VirtualMachineAdapter()
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuest item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuestInternal item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopy(IQuestGetter item, TranslationMask copyMask)
   at GridTrasitionCrashFix.Program.RunPatch(IPatcherState`2 state) in C:\Users\gameu\AppData\Local\Temp\Synthesis\0354znca.u2v\Git\skgkujwh.mzj\Runner\GridTrasitionCrashFix\Program.cs:line 23
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 54
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 53
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 81
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 50
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 49
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200

**Comment by OmniZenn** [comment]
Also experiencing something similar:

```
Compiling
No extra data to consider
("C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Git\gtdosnsb.ppc\Runner\GridTrasitionCrashFix"): "dotnet" "build \"GridTransitionCrashFix.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "ad3c1a88e3913a298b847938e0cab941a16251ef"
Running
(""): "dotnet" "run --project \"C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Git\gtdosnsb.ppc\Runner\GridTrasitionCrashFix\GridTransitionCrashFix.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"A:\Steam Folder\Steam\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"A:\My Games\Skyrim SE - Mods\tools\Synthesis\Data\Skyrim Special Edition\GridTransitionCrashFix\" --GameRelease SkyrimSE --ModKey \"Synthesis - Grid Transition CTD Fix.esp\" --LoadOrderFilePath \"C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Workspace\Synthesis - Grid Transition CTD Fix\Plugins.txt\" --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Workspace\Synthesis - Grid Transition CTD Fix\1 - GridTransitionCrashFix\Synthesis - Grid Transition CTD Fix.esp\" --PatcherName GridTransitionCrashFix"
Mutagen version: 0.36.3
Mutagen sha: fc2d89802dd42fe2558e6c754b35a130d7f2c09f
Synthesis version: 0.22.1
Synthesis sha: 820cdd4f57945993117de9613b154f002b930eeb
run-patcher --DataFolderPath "A:\Steam Folder\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "A:\My Games\Skyrim SE - Mods\tools\Synthesis\Data\Skyrim Special Edition\GridTransitionCrashFix" --GameRelease SkyrimSE --ModKey "Synthesis - Grid Transition CTD Fix.esp" --LoadOrderFilePath "C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Workspace\Synthesis - Grid Transition CTD Fix\Plugins.txt" --LoadOrderIncludesCreationClub --OutputPath "C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Workspace\Synthesis - Grid Transition CTD Fix\1 - GridTransitionCrashFix\Synthesis - Grid Transition CTD Fix.esp" --PatcherName GridTransitionCrashFix
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
Changed multiple conditions in QUST _M_QuestSolstheimCourierLetterHigh
Changed multiple conditions in QUST _M_QuestSolstheimCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestSolstheimCourierPotionHigh
Changed multiple conditions in QUST _M_QuestWhiterunCourierLetterHigh
Changed multiple conditions in QUST _M_QuestWhiterunCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestEastmarchCourierLetterHigh
Changed multiple conditions in QUST _M_QuestEastmarchCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestFalkreathCourierLetterHigh
Changed multiple conditions in QUST _M_QuestHaafingarCourierLetterHigh
Changed multiple conditions in QUST _M_QuestHjaalmarchCourierLetterHigh
Changed multiple conditions in QUST _M_QuestPaleCourierLetterHigh
Changed multiple conditions in QUST _M_QuestReachCourierLetterHigh
Changed multiple conditions in QUST _M_QuestRiftCourierLetterHigh
Changed multiple conditions in QUST _M_QuestWinterholdCourierLetterHigh
Changed multiple conditions in QUST _M_QuestFalkreathCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestHaafingarCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestHjaalmarchCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestPaleCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestReachCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestRiftCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestWinterholdCourierWeaponHigh
Changed multiple conditions in QUST _M_QuestEastmarchCourierPotionHigh
Changed multiple conditions in QUST _M_QuestFalkreathCourierPotionHigh
Changed multiple conditions in QUST _M_QuestHaafingarCourierPotionHigh
Changed multiple conditions in QUST _M_QuestHjaalmarchCourierPotionHigh
Changed multiple conditions in QUST _M_QuestPaleCourierPotionHigh
Changed multiple conditions in QUST _M_QuestReachCourierPotionHigh
Changed multiple conditions in QUST _M_QuestRiftCourierPotionHigh
Changed multiple conditions in QUST _M_QuestWhiterunCourierPotionHigh
Changed multiple conditions in QUST _M_QuestWinterholdCourierPotionHigh
Changed multiple conditions in QUST TownPortalUpdateLocation
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Noggog.BinaryMemoryReadStream.ReadUInt16() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Streams\Binary\BinaryMemoryReadStream.cs:line 151
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryCreateTranslation.ReadEntries(MutagenFrame frame, UInt16 objectFormat)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay.CustomCtor()
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay.QuestAdapterFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, Nullable`1 parseParams)
   at Mutagen.Bethesda.Skyrim.Internals.QuestBinaryOverlay.get_VirtualMachineAdapter()
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuest item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuestInternal item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopy(IQuestGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.Skyrim.QuestMixIn.DeepCopy(IQuestGetter item, TranslationMask copyMask)
   at GridTrasitionCrashFix.Program.RunPatch(IPatcherState`2 state) in C:\Users\omniz\AppData\Local\Temp\Synthesis\o4plgbj5.jea\Git\gtdosnsb.ppc\Runner\GridTrasitionCrashFix\Program.cs:line 23
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 68


```

**Comment by Arr1x** [comment]
I'll add to the voices. Another out of range error 

```
[303.9] Prepping state.
[304.5] Language: English
[309.4] Can use localization: True
[309.4] Localized: False
[309.4] Running patch.
[309.5] Changed multiple conditions in QUST _DL_QuestGuardAid
[309.7] Changed multiple conditions in QUST _M_QuestWhiterunCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestWhiterunCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestEastmarchCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestEastmarchCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestFalkreathCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestHaafingarCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestHjaalmarchCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestPaleCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestReachCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestRiftCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestWinterholdCourierLetterHigh
[309.7] Changed multiple conditions in QUST _M_QuestFalkreathCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestHaafingarCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestHjaalmarchCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestPaleCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestReachCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestRiftCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestWinterholdCourierWeaponHigh
[309.7] Changed multiple conditions in QUST _M_QuestEastmarchCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestFalkreathCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestHaafingarCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestHjaalmarchCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestPaleCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestReachCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestRiftCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestWhiterunCourierPotionHigh
[309.7] Changed multiple conditions in QUST _M_QuestWinterholdCourierPotionHigh
[310.5] Changed multiple conditions in QUST CYRWEBruma04
[310.5] Changed multiple conditions in QUST CYRWEBruma05
[310.5] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
[310.5]    at Noggog.BinaryMemoryReadStream.ReadUInt16() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Streams\Binary\BinaryMemoryReadStream.cs:line 149
[310.5]    at Mutagen.Bethesda.Skyrim.AVirtualMachineAdapterBinaryCreateTranslation.ReadEntries(MutagenFrame frame, UInt16 objectFormat)+MoveNext()
[310.5]    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
[310.5]    at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
[310.5]    at Mutagen.Bethesda.Skyrim.AVirtualMachineAdapterBinaryOverlay.CustomCtor()
[310.5]    at Mutagen.Bethesda.Skyrim.AVirtualMachineAdapterBinaryOverlay..ctor(MemoryPair memoryPair, BinaryOverlayFactoryPackage package)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestAdapterBinaryOverlay..ctor(MemoryPair memoryPair, BinaryOverlayFactoryPackage package)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestAdapterBinaryOverlay.QuestAdapterFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestAdapterBinaryOverlay.QuestAdapterFactory(ReadOnlyMemorySlice`1 slice, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestBinaryOverlay.get_VirtualMachineAdapter()
[310.5]    at Mutagen.Bethesda.Skyrim.QuestSetterTranslationCommon.DeepCopyIn(IQuest item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
[310.5]    at Mutagen.Bethesda.Plugins.Records.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
[310.5]    at Mutagen.Bethesda.Skyrim.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestSetterTranslationCommon.DeepCopyIn(IQuestInternal item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
[310.5]    at Mutagen.Bethesda.Skyrim.QuestSetterTranslationCommon.DeepCopy(IQuestGetter item, TranslationMask copyMask)
[310.5]    at GridTrasitionCrashFix.Program.RunPatch(IPatcherState`2 state) in C:\Users\Arrix\AppData\Local\Temp\Synthesis\2gav00br.sfl\Git\kzmijcfk.phz\Runner\GridTrasitionCrashFix\Program.cs:line 23
[310.5]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 99
[310.5] --- End of stack trace from previous location ---
[310.5]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 552
[310.5]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 449
[310.5]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 412
[342.3] No extra data to consider
```
