### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by Nesselm13** [ReaperAnon/GridTransitionCrashFix#4]
I am getting an error: 
System.ArgumentException: An item with the same key has already been added. Key: 03D403:Extended Encounters.esp
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Noggog.Cache`2.Add(TObject item) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Containers\Cache.cs:line 113
   at GridTrasitionCrashFix.Program.RunPatch(IPatcherState`2 state) in C:\Users\nesse\AppData\Local\Temp\Synthesis\y2dncro4.1ss\Git\jzn5fodg.xl2\Runner\GridTrasitionCrashFix\Program.cs:line 90
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 101
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 507
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 428
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 400

This seems really similar to problem referenced [here](https://github.com/tr4wzified/KnowYourEnemyPatcher/issues/23)

**Comment by alexzk1** [comment]
Running this repo alone works, so I moved it by the mouse to the top of the list in the Synt's patches and it worked ok.
